# https://medium.com/@bjnandi/containerize-your-full-stack-web-application-mern-with-docker-compose-4900156ba9dd
# https://www.geeksforgeeks.org/mern-stack/
version: "3.8"

services:
  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    # command: sh # Run bash instead of npm start
    # stdin_open: true # Keep stdin open
    # tty: true # Keep the terminal session open
    ports:
      - "80:80"
    depends_on:
      - server

  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    # command: sh # Run bash instead of npm start
    # stdin_open: true    # Keep stdin open
    # tty: true           # Keep the terminal session open
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - API_SPORTS_HOST=$API_SPORTS_HOST
      - API_SPORTS_API_KEY=$API_SPORTS_API_KEY
      - API_SPORTS_URL=$API_SPORTS_URL
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: ["mongod", "--quiet"]

volumes:
  mongodb_data:
